# Netlify configuration for Biblefresh Hebrew Bible Study website

[build]
  publish = "."

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirect common variations to main domain
[[redirects]]
  from = "/hebrew-bible-study"
  to = "/"
  status = 301

[[redirects]]
  from = "/dr-paul-hocking"
  to = "/#about"
  status = 301

[[redirects]]
  from = "/biblical-hebrew-tutoring"
  to = "/#tutoring"
  status = 301

# Handle 404s gracefully
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200